# Generic networking options
CONFIG_NETWORKING=y
CONFIG_NET_L2_OPENTHREAD=y
CONFIG_OPENTHREAD_COAP=y
CONFIG_OPENTHREAD_SLAAC=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_MAX_LEVEL=2
CONFIG_LOG_MODE_MINIMAL=n
#CONFIG_OPENTHREAD_LOG_LEVEL_DEBG=y
#CONFIG_BOOT_BANNER=y
#CONFIG_LOG_BACKEND_UART=y
# Disable USB console to avoid duplicate logs
#CONFIG_USB_DEVICE_STACK=n

CONFIG_BOOT_BANNER=n
#CONFIG_DEBUG=n
CONFIG_SPI=n
CONFIG_I2C=n
#compiler optimization
CONFIG_SIZE_OPTIMIZATIONS=y



# RAM configuration
CONFIG_INIT_STACKS=y
#CONFIG_MAIN_STACK_SIZE=20000
CONFIG_HEAP_MEM_POOL_SIZE=10192

CONFIG_MAIN_STACK_SIZE=30000
CONFIG_IDLE_STACK_SIZE=1024

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1024
# Configure Bluetooth LE

# Increase OpenThread worker thread stack to handle logging and CoAP handlers
CONFIG_OPENTHREAD_THREAD_STACK_SIZE=8192


# Compiler optimization
# CONFIG_COMPILER_OPT="-O3"
# CONFIG_COMPILER_OPT="-Os"

#CONFIG_GPIO=y

# Config Crypto
CONFIG_TINYCRYPT=y
CONFIG_TINYCRYPT_CTR_PRNG=y
CONFIG_TINYCRYPT_SHA256=y
CONFIG_TINYCRYPT_SHA256_HMAC=y
CONFIG_TINYCRYPT_SHA256_HMAC_PRNG=y
CONFIG_TINYCRYPT_ECC_DH=y
CONFIG_TINYCRYPT_ECC_DSA=y
CONFIG_TINYCRYPT_AES=y
CONFIG_TINYCRYPT_AES_CBC=y
CONFIG_TINYCRYPT_AES_CTR=y
CONFIG_TINYCRYPT_AES_CCM=y
CONFIG_TINYCRYPT_AES_CMAC=y

# Enable floating-point operations for pqm4
CONFIG_FP_HARDABI=y
CONFIG_FPU=y

# Network config
CONFIG_OPENTHREAD_PANID=4660
CONFIG_OPENTHREAD_XPANID="11:11:11:11:22:22:22:22"
CONFIG_OPENTHREAD_NETWORKKEY="00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd:ee:ff"
CONFIG_OPENTHREAD_CHANNEL=15
CONFIG_OPENTHREAD_NETWORK_NAME="OpenThreadDemo"

#CONFIG_OPENTHREAD_COAP=y
CONFIG_OPENTHREAD_COAP_BLOCK=y
# Set blockwise buffer size (default is 1024, increase if needed for large payloads)
CONFIG_OPENTHREAD_MESSAGE_BUFFER_SIZE=256
CONFIG_OPENTHREAD_NUM_MESSAGE_BUFFERS=256
#CONFIG_OPENTHREAD_CUSTOM_PARAMETERS="-DOPENTHREAD_CONFIG_COAP_MAX_BLOCK_LENGTH=512"

# For debugging
CONFIG_LOG_BUFFER_SIZE=16384
CONFIG_OT_COAP_SAMPLE_SERVER=y

# Add features required for FTD CLI
CONFIG_SHELL=y
CONFIG_OPENTHREAD_SHELL=y
CONFIG_OPENTHREAD_PING_SENDER=y